name: Supabase Activity Scheduler

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday midnight utc
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: curl https://iquiz-ai.vercel.app/api/unpause
